#%RAML 1.0 ResourceType

description: Collection of available <<resourcePathName>> in Payment-gateway.
get:
  headers:
    CLIENT-ID:
      description: |
        This is client id header for access
      required: true
      example: 5ae03353cdfc050c86afd331
    CLIENT-SECRET:
      description: |
        This is client secret header for access
      required: true
      example: 5ae03353tdfc050c86ssd331
  description: <<description>>
  responses:
    200:
      body:
        application/json:
          example: |
            <<exampleCollection>>
delete:
  headers:
    CLIENT-ID:
      description: |
        This is client id header for access
      required: true
      example: 5ae03353cdfc050c86afd331
    CLIENT-SECRET:
      description: |
        This is client secret header for access
      required: true
      example: 5ae03353tdfc050c86ssd331
  description: Delete <<resourcePathName>> by ID.
  responses:
    200:
      body:
        html/text:
          example: |
            <<exampleDelete>>